import AcademicTemplate from "../templates/AcademicTemplate";
import ProfessionalTemplate from "../templates/ProfessionalTemplate";
import ModernTemplate from "../templates/ModernTemplate";
import MinimalTemplate from "../templates/MinimalTemplate";

type ProgressLetterProps = {
  studentName: string;
  course: string;
  progress: string;
  instructor: string;
  date: string;
  template: "academic" | "professional" | "modern" | "minimal";
};

export default function ProgressLetter({
  studentName,
  course,
  progress,
  instructor,
  date,
  template,
}: ProgressLetterProps) {
  const title =
    template === "academic"
      ? "Academic Progress Letter"
      : template === "professional"
        ? "Professional Progress Report"
        : template === "modern"
          ? "Growth Progress Summary"
          : "Progress Letter";

  if (template === "academic") {
    return (
      <AcademicTemplate
        studentName={studentName}
        course={course}
        instructor={instructor}
        progress={progress}
        date={date}
      />
    );
  }
  if (template === "professional") {
    return (
      <ProfessionalTemplate
        studentName={studentName}
        course={course}
        instructor={instructor}
        progress={progress}
        date={date}
      />
    );
  }
  if (template === "modern") {
    return (
      <ModernTemplate
        studentName={studentName}
        course={course}
        instructor={instructor}
        progress={progress}
        date={date}
      />
    );
  }
  if (template === "minimal") {
    return (
      <MinimalTemplate
        studentName={studentName}
        course={course}
        instructor={instructor}
        progress={progress}
        date={date}
      />
    );
  }
  return (
    <div className={`letter-paper ${template}`}>
      <div className="letter-header">
        <h1 className={`letter-title ${template}`}>{title} </h1>

        <p className="letter-subtitle">Generated by Progress Letter Studio</p>
      </div>

      <div className="letter-section">
        <span className="letter-label">Student</span>

        <p className="letter-value">{studentName}</p>
      </div>

      <div className="letter-section">
        <span className="letter-label">Course</span>

        <p className="letter-value">{course}</p>
      </div>

      <div className="letter-section">
        <span className="letter-label">Instructor</span>

        <p className="letter-value">{instructor}</p>
      </div>

      <div className="progress-box">
        <span className="letter-label">Progress Summary</span>

        <p className="letter-value">{progress}</p>
      </div>

      <div className="signature">
        <div className="signature-line"></div>

        <p>{instructor}</p>

        <small>{date}</small>
      </div>
    </div>
  );
}
