import "../style/ModernTemplate.css";

type ModernTemplateProps = {
  studentName: string;
  course: string;
  instructor: string;
  progress: string;
  date: string;
};

export default function ModernTemplate({
  studentName,
  course,
  instructor,
  progress,
  date,
}: ModernTemplateProps) {
  return (
    <article className="modern-report">
      <header className="modern-hero">
        <span className="modern-tag">✨ PROGRESS LETTER STUDIO</span>

        <h1>Growth Progress Summary</h1>

        <p>A modern snapshot of achievements, milestones and future growth.</p>

        <div className="hero-date">{date}</div>
      </header>

      <section className="modern-cards">
        <div className="modern-card">
          <span>Student</span>
          <strong>{studentName}</strong>
        </div>

        <div className="modern-card">
          <span>Course</span>
          <strong>{course}</strong>
        </div>

        <div className="modern-card">
          <span>Instructor</span>
          <strong>{instructor}</strong>
        </div>
      </section>

      <section className="achievement-box">
        <h2>🚀 Achievement Summary</h2>

        <p>{progress}</p>
      </section>

      <section className="timeline">
        <h2>Growth Journey</h2>

        <div className="timeline-item">
          <div className="timeline-icon">🎯</div>

          <div>
            <strong>Started Learning</strong>
            <p>Built a solid foundation.</p>
          </div>
        </div>

        <div className="timeline-item">
          <div className="timeline-icon">💻</div>

          <div>
            <strong>Built Projects</strong>
            <p>Applied knowledge through real work.</p>
          </div>
        </div>

        <div className="timeline-item">
          <div className="timeline-icon">🏆</div>

          <div>
            <strong>Ready for Next Stage</strong>
            <p>Prepared for professional opportunities.</p>
          </div>
        </div>
      </section>

      <footer className="modern-footer">
        <div>
          <p className="modern-footer-p">
            <strong>Generated by</strong>
          </p>
          <p>Progress Letter Studio</p>
        </div>

        <div className="status-pill">COMPLETED</div>
      </footer>
    </article>
  );
}
